### PR TITLE
Require Chef 12 and resolve Chef 13 compatibility issues

### PR DESCRIPTION
**Pull request by tas50**
The yum cookbook's use of yum_repository is causing chef 13 compatibility failures. Using compat_resource should fix that up.

### CODE REVIEW

**Comment by BackSlasher** [comment]
no need for dnf anymore?

**Comment by damacus** [comment]
Nope

**Comment by BackSlasher** [comment]
@tas50 out of curiosity, what's wrong with `*` in markdown?

**Comment by tas50** [comment]
I have a markdown auto corrector that goes off some markdown guide somewhere. It likes - vs. *. As for DNF it's built into chef now so the need on the testing side to do the hack to get yum is no more.

**Comment by BackSlasher** [comment]
Neat.
Last point - I had issues with `compat_resource` because of it's magic-ness. Did we add a resource depending on it here?

**Comment by shortdudey123** [comment]
@BackSlasher the `yum` to `compat_resource` is due to most yum related resource being in chef core now which backports them to earlier versions (i think it was done last fall).  The DNF stuff was added in the latest stable release.

**Comment by BackSlasher** [comment]
But we removed the `yum` dependency as far as I can see, so why depend on `compat_resource`?

**Comment by damacus** [comment]
@BackSlasher habit from moving every cookbook from LWRP to custom_resources (which requires compat_resource) 

We'll need it in at some point in the future, so no harm done I think.

**Pull request merged**
