### PR TITLE
Add rhel-8 packages

### PR DESCRIPTION
**Pull request by sspans**
## Description

This adds support for rhel-8

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
Agreed it's a bit of a mess right no. Ignore MR @kitchen-porter 

It's due to all the test failing and it being pretty hard to test this cookbook on Virtual infrastructure.

**Comment by damacus** [comment]
Can you check this runs and works locally as expected, and post the results here please? 


Thanks!

**Comment by damacus** [comment]
Oh and you have some linting problems. Click on the Details for the lint step to get the linting errors from CircleCI 👍

**Comment by sspans** [comment]
The linting warnings seem the be unrelated rspec problems.
I have validated that the cookbook works on rhel-8 with these changes:

```
       Recipe: selinux::default
         * selinux_install[selinux os prep] action install
           * dnf_package[policycoreutils, selinux-policy, selinux-policy-targeted, libselinux-utils, mcstrans] action install (up to date)
           * directory[/etc/selinux] action create (up to date)
            (up to date)
         * selinux_state[SELinux Enforcing] action enforcing
           * execute[selinux-enforcing] action run (skipped due to not_if)
           * template[enforcing selinux config] action create (up to date)
            (up to date)
       Recipe: selinux_policy::install
         * selinux_policy_install[install] action install
           * dnf_package[policycoreutils-python-utils, selinux-policy-devel, setools-console, make] action install
             - install version 0:3.14.1-46.el8.noarch of package selinux-policy-devel
             - install version 0:4.1.1-11.el8.x86_64 of package setools-console
             - install version 1:4.2.1-9.el8.x86_64 of package make
```

**Comment by damacus** [comment]
Hey, this has been release to the supermarket as 2.2.0

**Pull request merged**
