### PR TITLE
Notify self fix

### PR DESCRIPTION
**Pull request by shortdudey123**
Rebased version of https://github.com/sous-chefs/selinux_policy/pull/57

Removes notification to self (new_resource) by inlining execute for
add/delete/modify. See #55 for more details.

### CODE REVIEW

**Comment by daften** [comment]
As mentioned in #56 I'd change the restorecon function to use find so it works for all cases, including regex, and remains fast.

Something like this (untested):
```
find / -regextype posix-egrep -regex '#{file_spec}' -type d -print0  2>/dev/null | xargs -0 restorecon -iR
```

**Comment by BackSlasher** [comment]
@daften I also think your idea is good. Would you mind creating a PR for this?

**Comment by daften** [comment]
Yes, no problem. Do I incorporate these changes in that PR too?

**Comment by BackSlasher** [comment]
I'd avoid these changes and just do:
find in restorecon command
regression testing (something that would fail on  the old code but pass with the new, like your regex case)

**Comment by daften** [comment]
Aight, will try to whip something up this week! :)

**Comment by daften** [comment]
PR #67 opened for this, sorry for the delay! Moving soon (and still looking for an appartment, so wish me luck with that :P )

**Pull request closed without merging**
