### PR TITLE
Mention method to generate modules

### PR DESCRIPTION
**Pull request by jhmartin**

### CODE REVIEW

**Comment by BackSlasher** [comment]
I don't understand what this documentation serves. If it should show how uncompiled SELinux modules show up, I think we can supply a link to some resource about building these.
Also, this should go to another place in the README, maybe in the introduction to the module resource.

**Comment by BackSlasher** [comment]
@jhmartin goes back to you (can't assign you apparently)

**Comment by jhmartin** [comment]
I added this as it matched the workflow I was going through and I felt would be reasonable for others -- try something, see the audit log failure, and want to generate a rule that resolves the issue.  Base audit2allow output isn't valid as a policy, but adding -r worked -- so I thought adding that nugget to the usage would help others trying to work through their SELinux rules.

**Comment by BackSlasher** [comment]
I appreciate that this might help the development, but I think it's in the wrong place in the README and not obvious enough. If you want to flesh it out into a couple of sentences or a short paragraph (possibly with links) about the whole process, that's better

**Comment by shortdudey123** [comment]
@jhmartin any updates on your end?

**Comment by shortdudey123** [comment]
Closing due to 9+ months of inactivity from author
Please open a new PR if you feel this is still needed

**Pull request closed without merging**
