### PR TITLE
Unbreak the cookbook

### LINKED ISSUE #90: ArgumentError with version 2.2.0
With the latest 2.2.0 release, this error comes up:

```
      ================================================================================
      Error executing action `create` on resource 'directory[/var/chef/cache/dockersock]'
      ================================================================================

      ArgumentError
      -------------
      wrong number of arguments (given 0, expected 1)

      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/selinux_policy/libraries/helpers.rb:8:in `use_selinux'
      /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:22:in `block (3 levels) in class_from_file'
      /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:14:in `block in class_from_file'

      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/selinux_policy/resources/module.rb

       21:   directory new_resource.directory do
       22:     only_if { use_selinux }
       23:   end
       24:

      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/selinux_policy/resources/module.rb:21:in `block in class_from_file'

      directory("/var/chef/cache/dockersock") do
        action [:create]
        default_guard_interpreter :default
        declared_type :directory
        cookbook_name "dltools"
        path "/var/chef/cache/dockersock"
        owner nil
        group nil
        mode nil
        only_if { #code block }
      end
```

### PR DESCRIPTION
**Pull request by sspans**
## Description

This reverts part of the earlier refactoring, to unbreak the cookbook.

### Issues Resolved

Fixes #90 

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by sspans** [comment]
Seems like this needs a bit more work

**Comment by PowerKiKi** [comment]
Tests were actually broken for the 2.2.0 release: https://circleci.com/gh/sous-chefs/selinux_policy/25. This PR does not seem to make it much worse than it already was.

@damacus, could you please comment on why a 2.2.0 was cut while unit tests were failing ? and are you in a position to release a 2.3.0 with passing tests in a timely fashion ?

**Comment by sspans** [comment]
Should be good to merge now, please review.

**Comment by PowerKiKi** [comment]
LGTM

Thank you for your work @sspans !

**Comment by sspans** [comment]
This actually repairs the refactoring, I'd welcome a review now.

**Comment by damacus** [comment]
Can you do me a little favour and confirm this runs locally please?

**Comment by sspans** [comment]
I can run additional tests on monday, which indeed seems worth it in this case.
We have a reasonable number of users of this cookbook, but I'll need some time
to run tests for those.

**Comment by damacus** [comment]
Thanks for your work on this one 🎉

**Comment by tnguyen14** [comment]
@sspans do you have any update on the tests?

**Comment by sspans** [comment]
I've seem to have found a small issue with the port resources, investigating this one now

**Comment by damacus** [comment]
Happy to release, thanks for your work here guys! 

If you can figure out how to test the (integration test or unit test), or need help doing that. 

Drop us a line in the sous-chefs channel on the chef community slack and we'll get something started

**Pull request merged**
