### PR TITLE
Add /sbin path to semanage and setsebool commands

### LINKED ISSUE #85: sh: semanage: command not found
### Cookbook version
latest

### Chef-client version
14.2
### Platform Details
RHEL 7.5 

### Scenario:
Chef client 14.2 changed the way execute works, from the release notes:

default_env Property in Execute Resource

The shell_out helper has been extended with a new option default_env to allow disabling Chef from modifying PATH and LOCALE environmental variables as it shells out. This new option defaults to true (modify the environment), preserving the previous behavior of the helper.

The execute resource has also been updated with a new property default_env that allows utilizing this the ENV sanity functionality in shell_out. The new property defaults to false, but it can be set to true in order to ensure a sane PATH and LOCALE when shelling out. If you find that binaries cannot be found when using the execute resource, default_env set to true may resolve those issues.

### Steps to Reproduce:
Use chef-client 14.2, run from cron (we use sudo seems to inherit env and run just fine that way).

### Expected Result:
Chef client to run cleanly

### Actual Result:
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '127'
      ---- Begin output of semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.
cfg' ----
      STDOUT: 
      STDERR: sh: semanage: command not found
      ---- End output of semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.cf
g' ----
      Ran semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.cfg' returned 127
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/selinux_policy/providers/fcontext.rb:92:in `block in class_from_file'

### PR DESCRIPTION
**Pull request by tnguyen14**
## Description
Add the full paths to `semanage` and `setsebool` commands so that they won't fail when run in an environment where `/sbin` is not part of `PATH.

### Issues Resolved
Fixes #85 #93 

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by tnguyen14** [comment]
This depends on #92 to be merged for the tests to pass again.

**Comment by sspans** [comment]
This will break RHEL, where setsebool  and semanage live in /usr/sbin

**Comment by tnguyen14** [comment]
@sspans I am on RHEL, and I see `/usr/sbin/semanage` symlinked to `/sbin/semanage`, and `/usr/sbin/setsebool` being the same binary as `/sbin/setsebool`.

**Comment by damacus** [comment]
@sspans is suggesting is one of the reasons I looked at moving away from absolute paths. 

We could do some sort of helper that we pass in the actions e.g.
```ruby
def semanage(action)
  binary = <<go figure out what the actual binary is here!>>
  %x(#{binary} #{action})
end
```

**Comment by tnguyen14** [comment]
How would you figure out the actual binary path?

**Comment by sspans** [comment]
There is a ready made solution we can borrow from the dnf/yum providers. I'll create a patch tomorrow.

**Comment by sspans** [comment]
I've created #97 to solve this in a slightly cleaner way.

Can you review/test that pull-request to see if it solves your issue?

**Comment by damacus** [comment]
superseded by #97

**Pull request closed without merging**
