### PR TITLE
[Fix] Use xargs vs -execdir in resource/fcontext.rb

### LINKED ISSUE #88: [BUG] CentOS 7.x find 4.5.11 has a fd leak in -execdir - Too many open files
### Cookbook Version
 2.0.1+
### Chef-client version 
12.x -> 14.x
### Platform Details
CentOS 7.x Current

### Scenario:

find (GNU findutils) 4.5.11 has a filedescriptor leak in -execdir. This has been patched in 4.5.12 (http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=183115d0) but currently CentOS 7.x runs on 4.5.11 (https://pkgs.org/download/findutils). 

This change is what created this bug.
https://github.com/sous-chefs/selinux_policy/pull/67/commits/4c574249527a26cda63a6b795750f00a1a2b61ba

### Steps to Reproduce:
Step to repo can be found at the bottom of this post.
http://git.savannah.gnu.org/cgit/findutils.git/commit/?id=183115d0

Easiest way to repo is create a bunch of folders and files and then run on centOS 7.x while lowering ulimits.

```ulimits -n 256; chef-client```

### Expected Result:
restorecon works

### Actual Result:
```
[2018-11-15T18:02:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-11-15T18:02:22+00:00] ERROR: selinux_policy_fcontext[/var/lib/kafka(/.*)?] (cf_kafka::_config line 66) had an error: Mixlib::ShellOut::ShellCommandFailed: selinux_policy_fcontext[/var/lib/kafka(/.*)?] (cf_kafka::_config line 66) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
STDOUT:
STDERR: find: Failed to save working directory in order to run a command on ‘00000000000000890135.log’: Too many open files
---- End output of ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] ----
Ran ["find", "/", "-regextype", "posix-egrep", "-regex", "/var/lib/kafka(/.*)?", "-execdir", "restorecon", "-iRv", "{}", ";"] returned 1
[2018-11-15T18:02:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### PR DESCRIPTION
**Pull request by Techcadia**
## Description
Support for fixing the FD leak by replacing the -execdir with xargs while still maintaining the same code.

*NOTE*: Currently I have yet to test this because I don't have time today. I will next week.

### Issues Resolved
#88

[List any existing issues this PR resolves]

### Check List
- [ ] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

Currently I have no idea how to test this since there where no tests provided.

Here is the best I can provide.

```
# diff <(find / -ignore_readdir_race -regextype posix-egrep -regex "/app/example(/.*)?" -prune -execdir echo {} +) <(find / -ignore_readdir_race -regextype posix-egrep -regex "/app/example(/.*)?" -prune -print0 2>/dev/null | xargs -0 -I {} echo {})
1c1
< ./example
---
> /app/example
```

Here is an example of current working code. I am wondering if there is a problem with using relative paths vs full paths.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by Techcadia** [comment]
@josephholsten Only question is do I need to worry about the danger request?

**Comment by damacus** [comment]
@Techcadia yes, if you could adda changelog entry, that'd be great.

**Comment by Techcadia** [comment]
@damacus Checking to see when we can get this merged. This is currently blocking another bug that was fixed in the 2.1+ as I am still pinned on 2.0.0. #85 is still broken and #94 fixes it.

**Comment by damacus** [comment]
Right that's awesome.

Apologies for taking so long in merging this one! It missed our weekly mop up in the Monday meeting. 
If anyone on this thread wants to become a more active maintainer of this cookbook, as it looks like you're all invested in getting this working, we'd be happy to have you on board! 

https://sous-chefs.org/becoming-a-member/

**Comment by damacus** [comment]
Thanks guys, this has been released as part of 2.3.3

**Pull request merged**
