### PR TITLE
Since it requires a type to add, and you can't add two of the same ty…

### PR DESCRIPTION
**Pull request by trilom**
…pe, it only makes sure to take into the account so the port_defined function will grep for the type, and not just /^/, which triggers when using any ports already defined by default.

Signed-off-by: Bryan Killian <bryan.killian@ardentmc.com>

### CODE REVIEW

**Comment by BackSlasher** [comment]
Thanks for the PR! Would you mind cleaning the name / description and provide some example cases?
I think I've got it, but not completely sure.

**Comment by BackSlasher** [comment]
@trilom yeah that's a lot of testing :)
I'm sorry I can't thoroughly review it as I'm not very into SELinux Chef things these days, but I think what we're really missing is regression testing, e.g. a testcase (kitchen based probably) that will fail without your "fix" to explain the problem you're trying to fix.
Apologies if this is what your test is currently doing and I didn't get that

**Comment by trilom** [comment]
Leaving a comment to let you know that there is a kitchen test now added that would fail at the current master head, the branch here corrects that problem.

**Comment by damacus** [comment]
Hey @trilom could you resolve the conflicts please? 

The metadata.rb conflict is a licence change to `Apache-2.0`.


thanks!

**Comment by trilom** [comment]
attempting to resolve, but this sat shelved for a while.  the fcontext.rb change should be dropped.

thanks

**Comment by damacus** [comment]
Looks good I'm going to pull in my foodcritic fix branch, which fixes the error you're seeing.

**Pull request merged**
