### PR TITLE
use chef/mixin/which to locate selinux binaries

### LINKED ISSUE #85: sh: semanage: command not found
### Cookbook version
latest

### Chef-client version
14.2
### Platform Details
RHEL 7.5 

### Scenario:
Chef client 14.2 changed the way execute works, from the release notes:

default_env Property in Execute Resource

The shell_out helper has been extended with a new option default_env to allow disabling Chef from modifying PATH and LOCALE environmental variables as it shells out. This new option defaults to true (modify the environment), preserving the previous behavior of the helper.

The execute resource has also been updated with a new property default_env that allows utilizing this the ENV sanity functionality in shell_out. The new property defaults to false, but it can be set to true in order to ensure a sane PATH and LOCALE when shelling out. If you find that binaries cannot be found when using the execute resource, default_env set to true may resolve those issues.

### Steps to Reproduce:
Use chef-client 14.2, run from cron (we use sudo seems to inherit env and run just fine that way).

### Expected Result:
Chef client to run cleanly

### Actual Result:
      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '127'
      ---- Begin output of semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.
cfg' ----
      STDOUT: 
      STDERR: sh: semanage: command not found
      ---- End output of semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.cf
g' ----
      Ran semanage fcontext -a -f a -t etc_t '/etc/nagios/nrpe.cfg' returned 127
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/selinux_policy/providers/fcontext.rb:92:in `block in class_from_file'

### PR DESCRIPTION
**Pull request by sspans**
## Description

This uses the which helper to solve #85 and #93 

### Issues Resolved

#85 and #93 
[List any existing issues this PR resolves]

### Check List
- [x] All tests pass. See https://github.com/sous-chefs/apache2/blob/master/TESTING.md
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please add labels to this Pull Request</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by damacus** [comment]
It might be a little tidier if we have a method for sebool/semanage which returns the path?

**Comment by sspans** [comment]
Investigating adding a helper

**Comment by tnguyen14** [comment]
Thanks Dan. When will 2.3.1 be pushed to supermarket?

**Comment by damacus** [comment]
I'll do that today. Thanks for the nudge

**Pull request merged**
