### PR TITLE
Fix for #55 - don't notify self

### PR DESCRIPTION
**Pull request by atward**
Removes notification to self (new_resource) by inlining execute for
add/delete/modify. See #55 for more details.

### CODE REVIEW

**Comment by daften** [comment]
Very nice! Thanks @atward 
This fixes one part of the problem in #55  but not the full problem, since for my use case, it still relabels one folder to high :)

**Comment by BackSlasher** [comment]
ty for PR.
Couple of quick comments:
* won't it generate duplicate resource warnings on multiple actions on the same resource (since each action redefines the `execute` resource)?
* Where did the `relabel` action go?
* Can we have regression tests for this? I think ChefSpec will do nicely

**Comment by atward** [comment]
1) That was my initial thought but it doesn't generate any CHEF-3694. Using chef-12.10 style it could be modified to an `edit_resource` or using chef-12.5 style the entire provider could be moved to a custom resource and it put into an action_class - but the overall result is the same.

2) Missed - i'll push an additional commit

3) I haven't used ChefSpec, we only use integration tests. But happy to take suggestions.

**Comment by BackSlasher** [comment]
1. I'm not familiar with the new and fancy Chef lingo. RE custom resources - back when I was working with it I found out it has bad support for legacy versions so I'm skeptic.
2. I'd prefer the `shell_out` solution - that sounded very neat.
3. See my testing in the Rakefile. If I managed to set it up, it should be ~easy to add something there
4. Please consider the `regexp` idea. @daften made an interesting suggestion in #56. I think you can be friends.

**Comment by atward** [comment]
@BackSlasher re: 2/4 I believe you're mixing up issues. This is a fix for #55, not #56/#54.

**Comment by BackSlasher** [comment]
Yeah I got confused. I wonder if that's the beginning of my decline :(
How does the lazy segment help? Or is this all about isolating the relabel action to a different resource so it doesn't mark the `fcontext` as updated?

**Comment by BackSlasher** [comment]
I think #60 is better. LMK if it's not answering your needs

**Comment by daften** [comment]
#60 just breaks it, since regexes aren't full paths and nothing is done to convert a regex to a full path. The regexes don't seem to expand, so the restorecon isn't executed successfully (at least not for me).
I still think looking towards #55 is appropriate. Although less elegant, I can confirm it works and is fast.

**Comment by daften** [comment]
The main problem is that restorecon as command expects a path, not a regex, while fcontext can work with regexes.
@BackSlasher

**Comment by BackSlasher** [comment]
So it seems. Maybe we can change `restorecon` to `find` with some regex and `-exec restorecon`?

**Comment by BackSlasher** [comment]
BTW I don't have a lot of context on this atm. @shortdudey123 ?

**Comment by shortdudey123** [comment]
I can look more something this week

FWIW i have been running with https://github.com/sous-chefs/selinux_policy/pull/66 (rebased version of this PR) in prod for over a month and have had zero problems so far

**Comment by daften** [comment]
I had problems with this way of working, because of regexes like this:
/var/lib/mysql-default(/.*)?
It tries this as path, removes last slash and everything after, still not a path, and then does a restorecon on /var/lib, which can take loooooong

That's why I proposed to change this to use find. Since fcontext accepts regexes, but restorecon doesn't. Find also works with regexes and it's still blazing fast in my setup.

**Comment by daften** [comment]
Since #66 is a rebased version of this, I'd close this PR in favor of it (can't do it myself)

**Comment by shortdudey123** [comment]
Closing, refer to rebased version of this PR for further comments
https://github.com/sous-chefs/selinux_policy/pull/66

**Pull request closed without merging**
