### PR TITLE
Notify self fix

### PR DESCRIPTION
**Pull request by shortdudey123**
Recreation of https://github.com/sous-chefs/selinux_policy/pull/66 since https://github.com/sous-chefs/selinux_policy/pull/67 does not fix the issue

### CODE REVIEW

**Comment by BackSlasher** [comment]
Grant would you mind contriubting a regression test so we won't mistake in
closing this again?

**Comment by shortdudey123** [comment]
Yup, working on it already :)

**Comment by daften** [comment]
This will reinstate the behaviour that regexes just WON't WORK with this cookbook :(

**Comment by shortdudey123** [comment]
superseded by https://github.com/sous-chefs/selinux_policy/issues/70

**Pull request closed without merging**
