### PR TITLE
Determine the filesystem of the file.

### PR DESCRIPTION
**Pull request by acranox**
Run find on that filesystem, with the -xdev option, and -execdir +
Fixes https://github.com/sous-chefs/selinux_policy/issues/71

### CODE REVIEW

**Comment by BackSlasher** [comment]
Thanks for the PR! I think we should have an attribute to disable this behavior, even if it defaults to true. Wrote it in the review

**Comment by acranox** [comment]
I can't imagine a situation where you want to disable this behavior.  But I also don't understand this whole codepath.  Using find to locate a file to relabel doesn't seem to make any sense.  If the resource is a file, relabel just the file.  If the resource is a directory, recursively relabel the directory and it's contents.
Personally, I think you should just revert https://github.com/sous-chefs/selinux_policy/pull/67
You fixed a performance issue while introducing a bug.
Do you want it done fast, or do you want to done reliably?  Just put it back to using restorecon, which actually works as designed.

**Comment by BackSlasher** [comment]
@acranox the main point of using `find` is catching regex labels, which are very much a thing. These cannot be passed into `restorecon`. You can get more context by looking at #56. I hope this explains the codepath :smile: 
Your comment suggests another idea - use some logic to check if the label is a regex (incomplete solution - check if the escaped version equals the raw version), and if so skip the `find` and go `restorecon`. If detecting a regex sounds too fancy, add an attribute instead.
WDYT?

**Comment by acranox** [comment]
That could make sense.
Maybe selinux_policy_fcontext shouldn't support regex's though?  But that's a design decision.
PR #56 still introduced a bug, IMHO.  It worked faster for daften, but in my case, the relabel runs for 10 minutes and then times out with a failure, or it exits with a failure because it's looking at /proc.  usage of 'find /' needs to be removed.
I can take another crack at improving the PR when I have time, but I'd still suggest you fix the bug.
I still think my PR is safer.  The missing behavior you've asked for would only apply if I was trying to relabel a directory that has different filesystems underneath it, and my regex will match files on multiple filesystems.

**Comment by BackSlasher** [comment]
Well, `selinux_policy_fcontext` is going to support regex because SELinux's file contexts support regex and it's a useful feature.
Also people are using this already (e.g. [here](https://github.com/brianbianco/redisio/blob/190a0e0bfb5190798e8aadfee1d1d63ba6218c31/providers/configure.rb#L132)).
RE the missing behavior, in this PR we're knowingly breaking something. I can imagine someone having that usecase (think someone symlinking a directory in `/var/www` to something mounted on a different volume), so we shouldn't break their experience without allowing them to revert to the old behavior.

**Comment by BackSlasher** [comment]
I'd hate to nag, but this still presents some interesting edge-cases, e.g. `/tmp/.`. 
The regexed files <> the literal filename. Are you that adversed to using an attribute to control regex/noregex behavior?
 @daften want to provide a second opinion here?

**Comment by daften** [comment]
Sorry, I've moved places last week, so wasn't really following up on anything.
I'd say having a flag to have regex support is fine IMO. I'd leave the default as using the new behaviour TBH, so with regex enabled.
How do you see it then, a simple if/else with the old and new code in the different cases? (so find | restorecon vs finding the upper dir)

**Comment by acranox** [comment]
I don't know how to do what you're asking.  You're going to have to fix this one yourself.
Feel free to close this PR.  PR #67 opened a can of worms.  I'm just going to start disabling :relabel in my cookbooks, and start using a manual call to restorecon until this cookbook works more reliably.  Thanks.

**Comment by daften** [comment]
PR #67 might have opened a can of worms, but it did solve a particular case. And what I (and I think @BackSlasher) are proposing (not asking) is adapting the resource, so there's an additional attribute (e.g. disable_regex), which is taken into account in the provider. If it's false (the default) the current behaviour is done, if it's true, the old code is used. It's a simple if/else, not really rocket science IMO :)

**Comment by acranox** [comment]
It solved a particular case of poor performance, but introduced a bug that causes failures.  You turned slow code into unreliable code.
The change you are asking for it not rocket science, but it's beyond what I can do.  I'm not a ruby developer.  I hope someone more experienced can fix this.

I reported the bug, and when no one stepped up to fix it, I submitted a PR like you requested.   Since it's not up to your standards, it's not going to get merged.  Sadly, I think you should have had this level of standards with the last PR that caused this behavior.  You put a call to **find /** into the code. Traversing the filesystem starting at root was bound to cause issues.  Reading the man page for find to learn about -xdev isn't rocket science either.  :)

**Comment by acranox** [comment]
Is this still blocked due to changes being requested?
If so, can you restate what's needed?

**Comment by BackSlasher** [comment]
I'm sorry for not reviewing your latest change @acranox, somehow I missed that.
I doubt your attribute works, but I may be rusty on the syntax.
Could we make your attribute the one decider whether we implement the "default" behavior or your specific one?
Personally, I think we could go with:
```
if new_resource.ignore_regex
    // Your logic, running restorecon on the filename
    res = shell_out!('restorecon', '-irv', new_resource.file_spec)
else
    // Original logic, doing some fancy stuff
    res_fs = shell_out!('stat', '--format', '%m', new_resource.file_spec).stdout.chomp
    res = shell_out!('find', res_fs, '-xdev', '-regextype', 'posix-egrep', '-regex', new_resource.file_spec, '-execdir', 'restorecon', '-iRv', '{}', '+')
end
```
After that, we need test cases proving the code works as expected (see `test/cookbooks/selinux_policy_test` directory).
Also, I'd default the attribute to run the fancy behavior first, just so we don't surprise anyone.
Also, please add your attribute to `README.md` for future generations to find.
That sounds like it for now, hope it's OK :smile:

**Comment by acranox** [comment]
Thanks, I appreciate the help, but I'm in over my head already on this.
I think I'm better off removing this cookbook from my environment, or  pinning to an older version that doesn't have this problem.  I hope you can take some piece of my attempts and incorporate them into a future release.

**Comment by BackSlasher** [comment]
I'm sorry to hear that. Leave that PR open, I'll try to get around to
adding some stuff.
The thing I'm missing is how to test the non-regex code, but it might come
to me.

Anyway, thanks for pointing this out!

*Nitzan Raz*
http://backslasher.net

**Comment by zachsmorgan** [comment]
I'd be willing to take over here, however your testing methodology is slightly different than what I've used in the past. Based on the diff and your existing tests, I would just be adding a resource (two resources?) to test/cookbooks/selinux_policy_test/recipes/fcontext.rb, verifying behavior when the target is on a "remote" filesystem - is that correct?

**Comment by BackSlasher** [comment]
@zachsmorgan that sounds about right. Note that we also have more "normal" tests using chefspec, but the primitive kitchen testing is bigger here, because I'm a primitive person (even more so when starting this)

**Comment by zachsmorgan** [comment]
Unga Bunga :)

**Comment by chewi** [comment]
I ran into yet another problem with using find in its current form, which is that too many files causes it to run out of file descriptors.

```
find / -regextype posix-egrep -regex "/srv/git/gitlab/public(/.*)?" -execdir restorecon -iRv {} \;
find: Failed to save working directory in order to run a command on ‘information_desk_person_tone5-2fde4e98dd11c5c29c89cad7cbb7bd2d5077dfad07913b20e01955b2d0dfad40.png’: Too many open files
```

Simply changing this to `-execdir {} +` is sufficient but I think I can make this much faster whilst also addressing the above concerns.

I also had the idea of checking the regular expression but in a smarter way. I would compare the regexp with the escaped form but not just to see if they were different. I would find the directory name of the common prefix between the two. In the above example, the common prefix is `/srv/git/gitlab/public` and the directory name is `/srv/git/gitlab`. This would help for all cases at least two levels deep such as `/foo/bar(/.*)?`. As well as fixing the `/proc` issue, this makes my own test 7x faster.

Concerned that this might not avoid the `/proc` issue entirely, I checked the find man page and found `-ignore_readdir_race`, which I think does exactly what we need.

> Normally, find will emit an error message when it fails to stat a file. If you give this option and a file is deleted between the time find reads the name of the file from the directory and the  time  it tries to stat the file, no error message will be issued.

I hadn't noticed this option before so I wondered whether it was new but actually it dates back to 2004 so we don't need to worry about it being missing.

This can be faster still. Appending `-prune` to the find conditions means that, having matched the earlier conditions, it won't bother traversing a directory if it finds one. We're already telling restorecon to operate recursively so what's the point of checking and passing every file within that directory if we know the directory itself is going to be passed anyway? If the regexp only matches specific files rather than directories then it still works because `-prune` does not cull files and `restorecon -R` works on files too. For me, this speeds things up another 3x.

So a 21x speed up, how about it? :grin: I'll get a PR ready...

**Comment by damacus** [comment]
Hi everyone! 

What's the current status of this PR?

**Comment by chewi** [comment]
Well my comment above got two hoorays so I filed #77 and nothing happened. Travis failed, which was mostly not related to my change, and I explained the other failure.

**Comment by damacus** [comment]
Time to checking again with this one! 

#77 has now been closed and merged. What else can we do to get this merged and shipped?

**Comment by chewi** [comment]
I think you can close this now, #77 dealt with it all.

**Comment by damacus** [comment]
Awesome, thanks!

**Pull request closed without merging**
