### PR TITLE
Massively speed up relabelling while addressing issues in #71 and #72

### PR DESCRIPTION
**Pull request by chewi**
* Don't start traversing from / if it can be avoided.
* Use faster -execdir {} + to avoid running out of file descriptors.
* Use -ignore_readdir_race to avoid errors traversing /proc.
* Use -prune to stop needlessly traversing directories that will have restorecon applied recursively anyway.

### CODE REVIEW

**Comment by chewi** [comment]
The FC085 error that Travis has raised was already there. The suggestion is to use `converge_by` but I don't know how to use that when the idempotence is dependent on the outcome of the block.

**Comment by damacus** [comment]
I'll fix the other errors. 

Can you see if it still converges correctly without FC085/converge_by please?

**Comment by damacus** [comment]
If I don't respond grab me on slack 👍

**Comment by chewi** [comment]
Did a kitchen test run with centos-6.8, centos-7.4, fedora-25, all good.

**Pull request merged**
